spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    validationQuery: SELECT 1
    testOnBorrow: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  minio:
    url: ${SPRING_MINIO_URL}
    username: ${SPRING_MINIO_USERNAME}
    password: ${SPRING_MINIO_PASSWORD}
    bucketName: ${SPRING_MINIO_BUCKETNAME}

jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}

server:
  port: 8081